### ISSUE TITLE
created xml does not work, renaming of  elements requirered 

### ISSUE THREAD

**Issue by jraschke** [megabert/bennoconf#1]
Hello,

the created xml does not work with benno 2.2.5
you must change the following things to get it working

`<domain sender="true" recipent="true" from="true" to="true" cc="true" bcc="true">  --> <domain sender="true" recipent="true" from="true" to="true" cc="true">`

`<monthlyjournal/> --> <monthlyfsjournal/>`
`<simpleContainer> --> <simplecontainer>`
`<configuredContainers> -->  <configuredcontainers>`
`<containerarchives> -->   </containerarchive>`
 `<jettyconfig> --> <jettyConfig>`

Sincerely,
Juergen

**Comment by megabert** [comment]
Script updated according to your comments.

Thanks!
